# Generated by Django 5.2.17 on 2026-09-18 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('json_body', 'JSON Body'), ('json_file', 'JSON File'), ('csv_file', 'CSV File')], max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_code', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('account_code', models.CharField(max_length=50)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('errors', models.CharField(blank=True, default='', max_length=70)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['run_id', 'valid'], name='bank_valida_run_id_ec60cc_idx')],
            },
        ),
    ]
