# Generated by Django 5.2.17 on 2026-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrecord',
            name='source_type',
            field=models.CharField(choices=[('json_file', 'JSON File'), ('csv_file', 'CSV File')], max_length=20),
        ),
    ]
