# Generated by Django 5.2.17 on 2026-09-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_validator', '0002_alter_bankrecord_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrecord',
            name='source_type',
        ),
    ]
