# Generated by Django 5.2.17 on 2026-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_validator', '0004_validationrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrecord',
            name='file_name',
        ),
        migrations.AddField(
            model_name='validationrun',
            name='errors_by_code',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bankrecord',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
