# Generated by Django 5.2.17 on 2026-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_validator', '0005_remove_bankrecord_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrecord',
            name='balance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankrecord',
            name='credit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankrecord',
            name='debit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
