# Generated by Django 5.0.6 on 2026-09-13 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["bank_code"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("period", models.CharField(blank=True, db_index=True, max_length=16)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("source_file", models.CharField(max_length=512)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("valid_count", models.IntegerField(default=0)),
                ("invalid_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("errors_by_code", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["file_hash"], name="validation__file_ha_1d2444_idx"
                    ),
                    models.Index(
                        fields=["bank_code", "period"],
                        name="validation__bank_co_43ca6c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvalidRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("raw_row", models.JSONField()),
                ("error_codes", models.JSONField(default=list)),
                ("error_messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invalid_records",
                        to="validation.validationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "row_number"],
                "indexes": [
                    models.Index(
                        fields=["run", "row_number"],
                        name="validation__run_id_5310e0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("bank_code", models.CharField(db_index=True, max_length=32)),
                ("period", models.CharField(db_index=True, max_length=16)),
                ("account_code", models.CharField(db_index=True, max_length=64)),
                ("debit", models.DecimalField(decimal_places=2, max_digits=18)),
                ("credit", models.DecimalField(decimal_places=2, max_digits=18)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "record_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("currency", models.CharField(blank=True, max_length=8)),
                ("branch_code", models.CharField(blank=True, max_length=32)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valid_records",
                        to="validation.validationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "row_number"],
                "indexes": [
                    models.Index(
                        fields=["run", "row_number"],
                        name="validation__run_id_fc0424_idx",
                    ),
                    models.Index(
                        fields=["bank_code", "period", "account_code"],
                        name="validation__bank_co_8a88b4_idx",
                    ),
                ],
            },
        ),
    ]
